name: LucemansCore
main: nl.lucemans.Core.Main
version: 1.0
author: MrDisk (Lucemans)
softdepends: [SkinsRestorer, Vault]
commands:
   lucemans:
      description: Gives information about the plugin.
      usage: /lucemans
   race:
      description: Gives information about the plugin.
      usage: /lucemans
   rename:
      description: Gives information about the plugin.
      usage: /lucemans
   lbook:
      description: Gives information about the plugin.
      usage: /lucemans